name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Type of version change."
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install npm packages
        run: npm ci

      - name: ENV 🌍
        run: env

      - name: Setup Git
        run: |
          git config user.name 'Myles Borins'
          git config user.email 'myles.borins@gmail.com'

      - name: bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags
